version: '2.2'
services:
  doodle:
    build:
      context: ./
      dockerfile: Dockerfile
    image: doodle
    environment:
      - DATABASE_HOST=127.0.0.1
      - DATABASE_USER=root
      - DATABASE_NAME=root
      - DATABASE_PORT=3306
    ports:
      - 8080:8080
    networks:
      - network1
    depends_on:
      - mysql-docker-container
    links:
      - mysql-docker-container

  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=doodle_polls
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - /data/mysql
    ports:
    - 3333:3306
 
networks:
  network1: